<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GameEngine.Features.Audio.Vorbis</RootNamespace>
    <AssemblyName>Audio.Vorbis</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NVorbis" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Audio\Audio.csproj" />
  </ItemGroup>
</Project>
