<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>GameEngine.Features.Audio.OpenAL</RootNamespace>
    <AssemblyName>Audio.OpenAL</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.OpenAL" />
    <PackageReference Include="Silk.NET.OpenAL.Soft.Native" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Audio\Audio.csproj" />
  </ItemGroup>
</Project>
