<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sprites.Tests</RootNamespace>
    <AssemblyName>SpritesTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Engine.Core\Engine.Core.csproj" />
    <ProjectReference Include="..\Sprites\Sprites.csproj" />
  </ItemGroup>
</Project>
