<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GameEngine.Tools.Cli.Tests</RootNamespace>
    <AssemblyName>GameEngineCliTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine.Tools.Cli\Engine.Tools.Cli.csproj" />
  </ItemGroup>
</Project>
