<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>GameEngine.Features.ToneMapping</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.OpenGL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Engine.Core\Engine.Core.csproj" />
    <ProjectReference Include="..\RenderPipeline\RenderPipeline.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ToneMappingTests" />
  </ItemGroup>
</Project>
