namespace GameEngine.Tools.AssetCompiler;

using System.Text;
using GameEngine.Core.Domain.Graphics;
using GameEngine.Features.ShaderAssets.Domain;
using GameEngine.Features.ShaderAssets.Infrastructure;

public sealed record ShaderReferenceGenerationRequest(
    string ProjectRoot,
    string ManifestPath,
    string OutputFile,
    string Namespace,
    string RootClassName = "GameShaders");

public sealed record ShaderReferenceGenerationResult(
    string OutputFile,
    bool Changed,
    int ShaderCount,
    int MaterialCount,
    int ParameterCount);

/// <summary>
/// Generates stable logical Shader, Material, and typed parameter references from shaders.json.
/// The generated API contains no GL objects and is safe to compile into game code.
/// </summary>
public sealed class ShaderReferenceCodeGenerator
{
    private sealed record GeneratedMember(string Identifier, string LogicalName);

    public ShaderReferenceGenerationResult Generate(ShaderReferenceGenerationRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.ProjectRoot);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.ManifestPath);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.OutputFile);
        GeneratedCodeUtilities.ValidateNamespace(request.Namespace);
        GeneratedCodeUtilities.ValidateIdentifier(
            request.RootClassName,
            "Generated Shader root class name");

        string projectRoot = Path.GetFullPath(request.ProjectRoot);
        if (!Directory.Exists(projectRoot))
            throw new DirectoryNotFoundException($"Project root '{projectRoot}' does not exist.");

        LoadedShaderAssetManifest loaded = ShaderAssetManifestLoader.Load(request.ManifestPath);
        string runtimeManifestPath = RequireRelativeToProject(
            projectRoot,
            loaded.ManifestPath,
            "Shader manifest");
        string outputFile = Path.GetFullPath(request.OutputFile);
        RequireUnderProject(projectRoot, outputFile, "Generated Shader reference output");
        if (!StringComparer.OrdinalIgnoreCase.Equals(Path.GetExtension(outputFile), ".cs"))
            throw new InvalidDataException("Generated Shader reference output must be a .cs file.");

        GeneratedMember[] shaders = CreateMembers(
            "Shader",
            loaded.Manifest.Shaders.Select(shader => shader.Name));
        GeneratedMember[] materials = CreateMembers(
            "Material",
            loaded.Manifest.Materials.Select(material => material.Name));
        var materialIdentifiers = materials.ToDictionary(
            member => member.LogicalName,
            member => member.Identifier,
            StringComparer.Ordinal);

        string source = RenderSource(
            request.Namespace,
            request.RootClassName,
            runtimeManifestPath,
            shaders,
            materials,
            loaded.Manifest.Materials,
            materialIdentifiers);
        bool changed = GeneratedCodeUtilities.WriteIfChanged(outputFile, source);
        return new ShaderReferenceGenerationResult(
            outputFile,
            changed,
            shaders.Length,
            materials.Length,
            loaded.Manifest.Materials.Sum(material => material.Uniforms.Count));
    }

    private static GeneratedMember[] CreateMembers(string kind, IEnumerable<string> logicalNames)
    {
        var identifiers = new Dictionary<string, string>(StringComparer.Ordinal);
        var result = new List<GeneratedMember>();
        foreach (string logicalName in logicalNames.OrderBy(value => value, StringComparer.Ordinal))
        {
            string identifier = GeneratedCodeUtilities.ToIdentifier(logicalName, kind);
            if (identifiers.TryGetValue(identifier, out string? existing))
            {
                throw new InvalidDataException(
                    $"{kind} names '{existing}' and '{logicalName}' both map to generated " +
                    $"identifier '{identifier}'. Rename one asset to make the C# API unambiguous.");
            }
            identifiers.Add(identifier, logicalName);
            result.Add(new GeneratedMember(identifier, logicalName));
        }
        return result.ToArray();
    }

    private static string RenderSource(
        string targetNamespace,
        string rootClassName,
        string runtimeManifestPath,
        IReadOnlyList<GeneratedMember> shaders,
        IReadOnlyList<GeneratedMember> materials,
        IReadOnlyList<MaterialAssetDefinition> definitions,
        IReadOnlyDictionary<string, string> materialIdentifiers)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.Append("namespace ").Append(targetNamespace).AppendLine(";");
        source.AppendLine();
        source.Append("public static class ").Append(rootClassName).AppendLine();
        source.AppendLine("{");
        source.Append("    public const string ManifestPath = ")
            .Append(GeneratedCodeUtilities.Literal(runtimeManifestPath))
            .AppendLine(";");
        source.AppendLine();
        AppendReferenceContainer(
            source,
            "Shaders",
            "global::GameEngine.Core.Domain.Graphics.ShaderRef",
            shaders);
        source.AppendLine();
        AppendReferenceContainer(
            source,
            "Materials",
            "global::GameEngine.Core.Domain.Graphics.MaterialRef",
            materials);
        source.AppendLine();
        source.AppendLine("    public static class Parameters");
        source.AppendLine("    {");
        foreach (MaterialAssetDefinition material in definitions
                     .OrderBy(value => value.Name, StringComparer.Ordinal))
        {
            string materialIdentifier = materialIdentifiers[material.Name];
            source.Append("        public static class ")
                .Append(materialIdentifier)
                .AppendLine();
            source.AppendLine("        {");
            GeneratedMember[] parameters = CreateParameterMembers(material);
            foreach (GeneratedMember parameter in parameters)
            {
                MaterialUniformAssetDefinition definition = material.Uniforms.Single(
                    value => StringComparer.Ordinal.Equals(value.Uniform.Name, parameter.LogicalName));
                source.Append("            public static readonly global::GameEngine.Core.Domain.Graphics.MaterialParameterRef<")
                    .Append(GetParameterType(definition.Uniform.Type))
                    .Append("> ")
                    .Append(parameter.Identifier)
                    .Append(" = new(Materials.")
                    .Append(materialIdentifier)
                    .Append(", ")
                    .Append(GeneratedCodeUtilities.Literal(parameter.LogicalName))
                    .AppendLine(");");
            }
            source.AppendLine("        }");
        }
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static GeneratedMember[] CreateParameterMembers(MaterialAssetDefinition material)
    {
        var identifiers = new Dictionary<string, string>(StringComparer.Ordinal);
        var result = new List<GeneratedMember>();
        foreach (MaterialUniformAssetDefinition uniform in material.Uniforms
                     .OrderBy(value => value.Uniform.Name, StringComparer.Ordinal))
        {
            string logicalName = uniform.Uniform.Name;
            string displayName = logicalName.Length > 1 && logicalName[0] == 'u' &&
                                 char.IsUpper(logicalName[1])
                ? logicalName[1..]
                : logicalName;
            string identifier = GeneratedCodeUtilities.ToIdentifier(
                displayName,
                $"Material '{material.Name}' parameter");
            if (identifiers.TryGetValue(identifier, out string? existing))
            {
                throw new InvalidDataException(
                    $"Material '{material.Name}' parameter names '{existing}' and '{logicalName}' " +
                    $"both map to generated identifier '{identifier}'.");
            }
            identifiers.Add(identifier, logicalName);
            result.Add(new GeneratedMember(identifier, logicalName));
        }
        return result.ToArray();
    }

    private static void AppendReferenceContainer(
        StringBuilder source,
        string containerName,
        string referenceType,
        IReadOnlyList<GeneratedMember> members)
    {
        source.Append("    public static class ").Append(containerName).AppendLine();
        source.AppendLine("    {");
        foreach (GeneratedMember member in members)
        {
            source.Append("        public static readonly ")
                .Append(referenceType)
                .Append(' ')
                .Append(member.Identifier)
                .Append(" = new(")
                .Append(GeneratedCodeUtilities.Literal(member.LogicalName))
                .AppendLine(");");
        }
        source.AppendLine("    }");
    }

    private static string GetParameterType(ShaderUniformType type) => type switch
    {
        ShaderUniformType.Float => "float",
        ShaderUniformType.Int => "int",
        ShaderUniformType.Vector2 => "global::System.Numerics.Vector2",
        ShaderUniformType.Vector4 => "global::System.Numerics.Vector4",
        _ => throw new InvalidDataException($"Unsupported material parameter type '{type}'.")
    };

    private static string RequireRelativeToProject(string projectRoot, string path, string kind)
    {
        RequireUnderProject(projectRoot, path, kind);
        return Path.GetRelativePath(projectRoot, path).Replace('\\', '/');
    }

    private static void RequireUnderProject(string projectRoot, string path, string kind)
    {
        string relative = Path.GetRelativePath(projectRoot, Path.GetFullPath(path));
        if (relative == ".." ||
            relative.StartsWith($"..{Path.DirectorySeparatorChar}", StringComparison.Ordinal) ||
            Path.IsPathRooted(relative))
        {
            throw new InvalidDataException($"{kind} '{path}' escapes project root '{projectRoot}'.");
        }
    }
}
